### ISSUE TITLE
Automatic SysRun behavior doesn't match manual SysRun behavior

### ISSUE THREAD

**Issue by TheEmeraldKytten** [Psychon-Dev-Studios/new_winline#12]
**Describe the bug**
The current implementation of automatically running commands on the system does not match the implementation for SysRun. This leads to weird errors, where using a command like "echo test" will result in an error while "sysRun echo test" will print "test" to the terminal.

**Expected behavior**
Running a system command (like echo) with arguments should behave like the sysRun command

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version:
 - WinLine Version: 3.7.2

**Comment by psychon-night** [comment]
Patched in 3.7.4
