### ISSUE TITLE
Enable users to disable malware checks without warning

### ISSUE THREAD

**Issue by TheEmeraldKytten** [Psychon-Dev-Studios/new_winline#13]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Enable users to disable malware checks without the warning prompt on every launch

**Describe alternatives you've considered**
We've considered completely removing the prompt

**Comment by psychon-night** [comment]
The only problem with this feature is that malware could abuse it to more easily compromise WinLine. We will not be implementing this feature
