### ISSUE TITLE
Upgrading to new config causes a crash

### ISSUE THREAD

**Issue by TheEmeraldKytten** [Psychon-Dev-Studios/new_winline#17]
**Describe the bug**
When upgrading to the new config API, WinLine will crash due to a failed import

**Desktop (please complete the following information):**
 - OS: Windows 10 & 11
 - WinLine Version: 3.13, 3.14

**Additional context**
This issue will be fixed with an emergency patch tomorrow. For now, please use this workaround:
1) Locate your WinLine installation (usually C:/ProgramData/winLine or /home/USERNAME/.winline)
2) Delete "config" from the directory
3) Create a new text file called `winline.conf`
4) Paste the contents of [this file](https://github.com/Psychon-Dev-Studios/new_winline/blob/main/defaultConfig314.conf) into the new file and SAVE it
5) Launch WinLine

**Comment by psychon-night** [comment]
Solved in version 3.15
